adventure_story = {
    "1": {
        "choice": "Explore the ancient forest.",
        "scenario": "You stand at the edge of an ancient forest, a sense of adventure in the air. Do you venture deeper or set up camp for the night?",
        "choice1_id": "2",
        "choice2_id": "3",
    },
    "2": {
        "choice": "Venture deeper into the forest.",
        "scenario": "As you walk deeper, the trees grow denser. You hear rustling in the bushes. Do you investigate the sound or continue walking?",
        "choice1_id": "4",
        "choice2_id": "5",
    },
    "3": {
        "choice": "Set up camp for the night.",
        "scenario": "You decide to camp for the night. As you sit by the fire, you hear a distant howl. Do you check it out or stay by the fire?",
        "choice1_id": "6",
        "choice2_id": "7",
    },
    "4": {
        "choice": "Investigate the sound.",
        "scenario": "You approach the bushes cautiously. A small fox jumps out and runs away. Do you follow the fox or return to the path?",
        "choice1_id": "8",
        "choice2_id": "9",
    },
    "5": {
        "choice": "Continue walking.",
        "scenario": "You ignore the rustling and keep walking. Suddenly, you find a hidden clearing with a sparkling pond. Do you drink from the pond or rest beside it?",
        "choice1_id": "10",
        "choice2_id": "11",
    },
    "6": {
        "choice": "Check it out.",
        "scenario": "You decide to investigate the howl. As you walk, you stumble upon an old ruin. Do you enter the ruin or leave it be?",
        "choice1_id": "12",
        "choice2_id": "13",
    },
    "7": {
        "choice": "Stay by the fire.",
        "scenario": "You choose to stay by the fire, but the howl grows closer. Suddenly, a shadowy figure appears. You decide it's best to remain quiet, and the figure eventually leaves. You've survived the night and decides that this adventure is too much for you so you went home.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "8": {
        "choice": "Follow the fox.",
        "scenario": "You follow the fox through the underbrush. It leads you to a hidden treasure. Do you take the treasure or leave it?",
        "choice1_id": "14",
        "choice2_id": "15",
    },
    "9": {
        "choice": "Return to the path.",
        "scenario": "You decide it's not worth the risk and return to the path. Suddenly, you encounter a wise old sage. Do you ask for advice or continue on your journey?",
        "choice1_id": "16",
        "choice2_id": "17",
    },
    "10": {
        "choice": "Drink from the pond.",
        "scenario": "You drink from the pond and feel rejuvenated. Suddenly, you hear a voice asking you to choose a path. Do you take the left path or the right path?",
        "choice1_id": "18",
        "choice2_id": "19",
    },
    "11": {
        "choice": "Rest beside the pond.",
        "scenario": "As you rest, you see magical creatures emerge from the water. You decide to join them in their games, and they lead you to a hidden realm. You've found a new home.",
    },
    "12": {
        "choice": "Enter the ruin.",
        "scenario": "Inside the ruin, you find ancient artifacts. Do you take one or leave them as they are?",
        "choice1_id": "20",
        "choice2_id": "21",
    },
    "13": {
        "choice": "Leave it be.",
        "scenario": "You decide not to enter the ruin. As you turn to leave, you spot a hidden path. Do you explore the path or head back to camp?",
        "choice1_id": "22",
        "choice2_id": "23",
    },
    "14": {
        "choice": "Take the treasure.",
        "scenario": "You take the treasure, but it's cursed! You feel a dark energy enveloping you. You wander aimlessly until you lose your way. You've succumbed to the curse.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "15": {
        "choice": "Leave the treasure.",
        "scenario": "You leave the treasure untouched. As you turn to leave, you notice a glimmer in the ground—a hidden gem! You collect it and feel lucky.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "16": {
        "choice": "Ask for advice.",
        "scenario": "You seek the sage's wisdom. They reveal a secret path that leads to a safe village. You've found your way to safety.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "17": {
        "choice": "Continue on your journey.",
        "scenario": "You choose to ignore the sage and continue. Unfortunately, you get lost and eventually run out of provisions. You succumb to hunger.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "18": {
        "choice": "Take the left path.",
        "scenario": "You choose the left path, which leads to a beautiful meadow. You decide to rest here and enjoy the tranquility.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "19": {
        "choice": "Take the right path.",
        "scenario": "You take the right path and encounter a fierce creature guarding a bridge. You must fight or flee.",
        "choice1_id": "24",
        "choice2_id": "25",
    },
    "20": {
        "choice": "Take an artifact.",
        "scenario": "You take an artifact, and suddenly the ruins begin to collapse. You escape just in time, but the artifact holds a dark secret. You're haunted by its power.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "21": {
        "choice": "Leave the artifacts.",
        "scenario": "You leave the artifacts untouched. As you exit, you find a hidden exit leading to a magical grove where you find peace.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "22": {
        "choice": "Explore the hidden path.",
        "scenario": "You explore the hidden path and discover a secret waterfall. The beauty is mesmerizing, and you decide to stay here forever.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "23": {
        "choice": "Head back to camp.",
        "scenario": "You head back to camp, feeling uneasy. During the night, strange noises haunt you, leaving you restless until dawn.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "24": {
        "choice": "Fight the creature.",
        "scenario": "You bravely fight the creature and manage to defeat it. You cross the bridge and find a treasure chest filled with gold.",
        "choice1_id": "",
        "choice2_id": "",
    },
    "25": {
        "choice": "Flee from the creature.",
        "scenario": "You choose to flee, but the creature chases you. You manage to escape, but you're lost and alone in the forest.",
        "choice1_id": "",
        "choice2_id": "",
    },
}
